import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync('index.html','utf8');
const core=html.slice(html.indexOf('function rand(){'),html.indexOf('function updatePanel('));
const ctx={Math,Uint8Array,Int32Array,Map,document:{getElementById:id=>id==='seed'?{value:'42'}:{innerHTML:''}},updatePanel:()=>{}};
vm.createContext(ctx);
vm.runInContext(`const W=48,H=36,S=52;let seed,rng,tiles,agents,homes,trees,berries,events,day,stock,selected,scale,ox,oy,uid,reachable,depot;${core}`,ctx);
const run=s=>vm.runInContext(s,ctx);
run('createWorld()');
run(`const homeSite = Array.from(reachable).findIndex((r,i)=>r&&tiles[i]!=='water'&&i%48>4&&Math.floor(i/48)>4);homes.push({id:999,x:homeSite%48,y:Math.floor(homeSite/48),level:1,owner:agents[0].name});agents[0].home=999;agents[0].x=depot.x+.5;agents[0].y=depot.y+.5;agents[0].energy=10;agents[0].hunger=0;agents[0].resting=false;`);
const initial=run('Math.hypot(agents[0].x-homes[0].x-.5,agents[0].y-homes[0].y-.5)');
run('step()');
assert.equal(run('agents[0].state'),'Идёт домой отдыхать');
assert.ok(run('agents[0].energy')<11,'resident must not gain sleep energy before reaching home');
for(let i=0;i<900;i++)run('step()');
assert.ok(run('agents[0].energy')>=22,'resident failed to recover energy');
assert.ok(run('Math.hypot(agents[0].x-homes[0].x-.5,agents[0].y-homes[0].y-.5)')<initial,'did not travel toward home');
run('agents[1].age=85;agents[1].health=.001');
run('step()');
assert.equal(run('agents[1].state'),'Умер от старости');
console.log('Household sleep path, energy recovery, and old-age death events passed');
