import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync('index.html','utf8');
const code=html.slice(html.indexOf('function rand(){'),html.indexOf('function updatePanel('));
const memory=new Map();
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{value:'42',innerHTML:'',textContent:''});return elements.get(id)}
const ctx={Math,Uint8Array,Int32Array,Map,localStorage:{setItem:(k,v)=>memory.set(k,v),getItem:k=>memory.get(k)||null},document:{getElementById:element},updatePanel:()=>{}};
vm.createContext(ctx);
vm.runInContext(`const W=48,H=36,S=52;let seed,rng,tiles,agents,homes,trees,berries,events,day,stock,selected,scale,ox,oy,uid,reachable,depot;${code}`,ctx);
const run=s=>vm.runInContext(s,ctx);
run('createWorld()');
for(let i=0;i<520;i++)run('step()');
const before=JSON.stringify(run('worldSnapshot()'));
assert.ok(run('saveWorld()'));
run('createWorld()');
assert.ok(run('loadWorld()'));
assert.equal(JSON.stringify(run('worldSnapshot()')),before,'roundtrip should preserve all state');
const second=JSON.stringify(run('worldSnapshot()'));
run('step()');
const evolved=JSON.stringify(run('worldSnapshot()'));
run('restoreWorld(JSON.parse('+JSON.stringify(second)+'))');
run('step()');
assert.equal(JSON.stringify(run('worldSnapshot()')),evolved,'same RNG and state must produce the same next tick');
const broken=JSON.parse(before);broken.tiles=[];
assert.throws(()=>run('restoreWorld('+JSON.stringify(broken)+')'),/карта/);
assert.equal(JSON.stringify(run('worldSnapshot()')),evolved,'invalid saves must not change running world');
memory.set('AETHERRA_WORLD_V1','{broken JSON');
assert.equal(run('loadWorld()'),false);
assert.equal(JSON.stringify(run('worldSnapshot()')),evolved,'malformed storage must not change world');
console.log('World saves: snapshot roundtrip, deterministic continuation, malformed and incompatible save protection passed');
